version: "2"
linters:
  default: all
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/gruntwork-io/terragrunt/config
            - github.com/gruntwork-io/terragrunt/options
            - github.com/wakeful/atlantis-gen-yaml/internal/common
            - github.com/wakeful/atlantis-gen-yaml/internal/parser
            - github.com/wakeful/atlantis-gen-yaml/internal/template
            - github.com/wakeful/atlantis-gen-yaml/internal/terragrunt
  exclusions:
    generated: disable
    rules:
      - linters:
          - exhaustruct
          - funlen
          - testpackage
          - varnamelen
        path: _test.go
      - linters:
          - revive
        path: internal
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
