linters:
  enable-all: true
  disable:
    - exhaustruct
    - exportloopref
issues:
  exclude-rules:
    - path: _test.go
      linters:
        - funlen
        - paralleltest
        - testpackage
        - varnamelen
linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/gruntwork-io/terragrunt/config
          - github.com/gruntwork-io/terragrunt/options
          - github.com/wakeful/atlantis-gen-yaml/pkg/common
          - github.com/wakeful/atlantis-gen-yaml/pkg/parser
          - github.com/wakeful/atlantis-gen-yaml/pkg/template
          - github.com/wakeful/atlantis-gen-yaml/pkg/terragrunt
