linters:
  enable-all: true
  disable:
    - tenv
issues:
  exclude-rules:
    - path: _test.go
      linters:
        - exhaustruct
        - funlen
        - paralleltest
        - testpackage
        - varnamelen
linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/gruntwork-io/terragrunt/config
          - github.com/gruntwork-io/terragrunt/options
          - github.com/wakeful/atlantis-gen-yaml/internal/common
          - github.com/wakeful/atlantis-gen-yaml/internal/parser
          - github.com/wakeful/atlantis-gen-yaml/internal/template
          - github.com/wakeful/atlantis-gen-yaml/internal/terragrunt
